baseURL = "https://moragsimpson.co.uk/"
languageCode = "en-us"
title = "Morag Simpson"
theme = "timer-hugo"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Navbar Menus
[[menu.main]]
name    = "Home"
url     = "/"
weight  = 1
[[menu.main]]
name    = "Choirs"
url     = "choirs"
weight  = 3
[[menu.main]]
name    = "Lessons"
url     = "lessons"
weight  = 4
[[menu.main]]
name    = "Blog"
url     = "blog"
weight  = 5
#[[menu.main]]
#name    = "Shop"
#url     = "shop"
#weight  = 6
[[menu.main]]
name    = "Contact"
url     = "contact"
weight  = 7

# Site Params
[params]
home = "Home"
logo = "images/logo.png"
dateFormat = "6 January 2006"
# Meta data
description = "Airspace Hugo theme"
author = "Themefisher"
# Google Analitycs
googleAnalitycsID = "Your ID"
# contact form action
contactFormAction = "#" # contact form works with https://formspree.io

# Banner Section
[params.banner]
enable  = true
bgImage = "images/slider.jpg"
heading = "Morag Simpson MA LRAM LTCL"
description = "Westhill Music Studio simpsonmorag@gmail.com / 07818 464546"

# flip text
[[params.banner.flipText]]
title   = "MUSIC TEACHER"
[[params.banner.flipText]]
title   = "CHOIR DIRECTOR"
[[params.banner.flipText]]
title   = "AUTHOR"

# Homepage About Section
[params.about]
enable  = true
title   = "Lessons & Choirs"
content = "LESSONS GIVEN IN PIANO/SINGING/THEORY AND RECORDER IN WESTHILL -  Phone for further details. <br> Preloved music for sale"
image   = "images/about/about.jpg"

# Call to Action
[params.cta]
enable  = true
title   = "Contact"
content = "3 Crombie Circle, Westhill, AB32 6PY <br> simpsonmorag@gmail.com <br> 07818 44546"

# Portfolio Section On Homepage
[params.portfolio]
enable  = false
title   = "Latest Works"
subtitle= "Aliquam lobortis. Maecenas vestibulum mollis diam. Pellentesque auctor neque nec urna. Nulla sit amet est. Aenean posuere tortor sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus."

# social icon
[[params.socialIcon]]
icon = "ion-social-facebook"
url = "https://www.facebook.com/profile.php?id=100056147393106"

[[params.socialIcon]]
icon = "ion-social-youtube"
url = "https://www.youtube.com/channel/UCyCZoTmEr9Cm1uzYgy32_hA"
